name: Auto Versioning

on: [pull_request]
#  push:
#    paths:
#     - 'src/main/groovy/br/com/luisrjaeger/airwatch/**'

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Run increase version
      run: |
        ls
        cd ..
        ls
      shell: bash
